### ISSUE TITLE
Cannot set dataBinding in topekaui module

### ISSUE THREAD

**Issue by mkrol91** [googlecodelabs/android-topeka#11]
When i try to add

dataBinding {
        enabled true
}

to topekaui module i meet issue mentioned below:
https://issuetracker.google.com/63814741 for details

and when i than try to add  baseFeature = true to this module i get:

>  A dependent feature was defined but no package ID was set. You are probably missing a feature dependency in the base feature.

Any ideas?

**Comment by alibitek** [comment]
Because of that bug. you have to remove data binding from non base modules Gradle files.

This means you also need to refactor the code in topekaui feature module, CategorySelectionActivity class, onCreate method and the referenced content XML layout file and remove the data binding calls from it.

See:
- https://github.com/alibitek/android-topeka/blob/self/topekaui/src/main/java/com/google/samples/apps/topeka/ui/activity/CategorySelectionActivity.java#L64
- https://github.com/alibitek/android-topeka/blob/self/topeka-base/src/main/res/layout/activity_category_selection.xml#L16

**Comment by jkingyens** [comment]
Data bindings from non-base module no longer need to be removed. Please update your repo and use Android Studio 3.1 preview to build the project and complete the codelab steps. Thanks!
