### ISSUE TITLE
feedback - add more information for google play upload

### ISSUE THREAD

**Issue by akhatri** [googlecodelabs/android-topeka#16]
Overall it's a great tutorial but there are a few things lacking especially if someone wants to test out an instant app via Google Play Console upload

- I have run into quite a few issues regarding URL filters. By following the tutorial and adding the App links, it appears the App Manifest file incorrectly generates these bits. I went through https://stackoverflow.com/questions/44621165/upload-failed-you-should-use-both-http-and-https-as-schemes-for-your-web-intent to find a solution, basically by creating separate entries in the data tag within intent-filter
- Using example URLs don't seem to work for release versions. Are there any sample URLs that would help in creating a working end-to-end project right until Google Play

`Your site 'example.com' could not be reached at this time to verify it has been linked through the Digital Assets Link protocol to your app. Check your site's URL and try again later.`

Thanks

**Comment by jkingyens** [comment]
Thank you for the feedback akhatri. To do a full test yourself you will need a custom domain/URL that you own yourself. This is because the URLs, verification and app are all tied together using the signing key of the developer. If you want to reproduce this yourself the best option is to purchase a domain and replace all sample URLs with your own. Then follow publishing steps such as those you see on stackover flow to ensure the APK successfully publishes. Thanks!
